### ISSUE TITLE
Avx512 support?

### ISSUE THREAD

**Issue by oscarbg** [OpenSWR/openswr-mesa#14]
Hi,
Saw at Idf that avx512 is coming soon to openswr.. Interested to study the code on how to efficiently use it for raster purposes.. And although no current HW supports it. with Intel SDE we could run the code..
Some ETA?

**Comment by BruceCherniak** [comment]
Hello.  Yes, OpenSWR will contain AVX512 code optimization, however, we cannot yet offer a specific ETA.  Please stay tuned and thank you for your interest in OpenSWR.
