### ISSUE TITLE
single build that supports offscreen and onscreen rendering with openswr

### ISSUE THREAD

**Issue by samfux84** [OpenSWR/openswr-mesa#17]
Hi,

I am new to building mesa, therefore my question might be a beginners question. I would like to build ParaView 5.1.0 with mesa using openswr on a HPC cluster (no GPU's available, but CPU's support avx and some even avx2).

Is it possible to do a single build of openswr-mesa, that supports offscreen (osmesa) and onscreen (mesa) rendering, using openswr in both cases ? Or do I have to do multiple builds of openswr-mesa ?

I tried to run the configure script with the following options:

`[sfux@develop01 openswr-mesa]$ ./configure --prefix=/cluster/apps/mesa/11.3.0/x86_64 --enable-xlib-glx --enable-gallium-osmesa --with-gallium-drivers=swr --disable-dri --disable-egl --enable-texture-float --disable-xvmc --disable-llvm-shared-libs`

and got the error message:

`configure: error: gallium_osmesa requires the gallium swrast driver`

Does this mean, that openswr can not be used for osmesa ?

This is a bit confusing, since the last sentence in the "Overview" paragraph https://github.com/OpenSWR/openswr/blob/master/README.md states that openswr also has an osmesa interface.

Could you please provide me some help with this issue.

Best regards

Sam

**Comment by BruceCherniak** [comment]
Hi Sam,

Apologies for not replying sooner.  OpenSWR can, indeed, be used with osmesa.  Your configure options are nearly correct.  Add "swrast" to the gallium drivers ("--with-gallium-drivers=swrast,swr"), that should take care of it.  Then, when you run "export GALLIUM_DRIVERS=swr" to select OpenSWR over the default llvmpipe driver.

Sorry for any confusion.

Bruce

**Comment by samfux84** [comment]
Hi Bruce,

thank you very much for your reply. Now it compiles fine.

Best regards

Sam
