### ISSUE TITLE
[master] error: invalid conversion from 'pipe_context* (*)(pipe_screen*, void*)' to 'pipe_context* (*)(pipe_screen*, void*, unsigned int)'

### ISSUE THREAD

**Issue by ignatenkobrain** [OpenSWR/openswr-mesa#3]
I applied patches to master branch of mesa, but it won't compile.

```
swr_screen.cpp: In function 'pipe_screen* swr_create_screen(sw_winsys*)':
swr_screen.cpp:649:32: error: invalid conversion from 'pipe_context* (*)(pipe_screen*, void*)' to 'pipe_context* (*)(pipe_screen*, void*, unsigned int)' [-fpermissive]
    screen->base.context_create = swr_create_context;
                                ^
Makefile:1011: recipe for target 'swr_screen.lo' failed
```

**Comment by timrowley** [comment]
gallium changed some of the internal APIs between 11.0 and the current master.  In this case a flags parameter was added to the context_create callback.  For experimentation purposes this can be ignored for now - just add an "unsigned flags" arg to swr_create_context in swr_context.{h,cpp}.

I should note that we haven't tried running on the master branch.  You may encounter other difficulties.

**Comment by ignatenkobrain** [comment]
> I should note that we haven't tried running on the master branch. You may encounter other difficulties.

That's why I want to test it :)

**Comment by ignatenkobrain** [comment]
https://github.com/ignatenkobrain/openswr-mesa/commit/fe9e5f557953d3c4b9c3cac6be0ff29d97c3f2c7

Here is a patch for this. I will test it and will let you know, but actually I don't think that this will somehow break workability.

**Comment by BruceCherniak** [comment]
We've recently added a "master-openswr" branch, which is the OpenSWR code merged against the current master.  This has become our development branch.  Please use this branch if you'd like to continue working with OpenSWR.  Thanks for your help.
