### ISSUE TITLE
fatal error: llvm/PassManager.h: No such file or directory

### ISSUE THREAD

**Issue by ignatenkobrain** [OpenSWR/openswr-mesa#5]
```
In file included from swr_tex_sample.cpp:48:0:
./rasterizer/jitter/JitManager.h:58:30: fatal error: llvm/PassManager.h: No such file or directory
```

But actually I have it under:
`/usr/include/llvm/IR/PassManager.h`

**Comment by timrowley** [comment]
That error sounds like you're building against llvm 3.7 or newer (I've just been working on code changes to allow that) - the code on github only supports llvm 3.6.  3.6 had the pass manager in the top-level llvm include directory; 3.7+ moves it to llvm/IR with a changed API.

**Comment by timrowley** [comment]
The current code supports llvm 3.6, 3.7, and 3.8.  This should fix the problem you're seeing.
